### ISSUE TITLE
title 重复

### ISSUE THREAD

**Issue by hao1032** [baotlake/periodic-table-pro#2]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/4860962/231220748-85b53bbd-c8db-494b-bc61-b5bdb065ac59.png">

**Comment by baotlake** [comment]
感谢反馈，[206c2c5](https://github.com/baotlake/periodic-table-pro/commit/206c2c5fc207bbacb124e21d18d38a0761d7913c) 提交已经修复这个问题。
