### ISSUE TITLE
抄袭的过分了吧

### ISSUE THREAD

**Issue by Kyant0** [baotlake/periodic-table-pro#6]
连界面都是一样的，现在新版变了一点界面，你的还是老界面。

![Screenshot_20240415-102642](https://github.com/baotlake/periodic-table-pro/assets/76829190/171d4e4c-9b92-4d20-83f6-194ab709a45a)

![Screenshot_20240415-102646](https://github.com/baotlake/periodic-table-pro/assets/76829190/9f7a99e9-11a8-49a7-a0d2-0777677e8801)

**Comment by Kyant0** [comment]
已联系作者

**Comment by baotlake** [comment]
这个项目开始时确实有借鉴参考一些其他的元素周期表（包括您说的这个APP），您提到的这个APP也是一个很棒的工具。

至于您提到的抄袭，您可以把本项目当作是它的一个web端的“复刻”，这么看的话是不是还是有挺多地方不够“还原”的？

**Comment by Kyant0** [comment]
数据是从哪儿来的呢

**Comment by baotlake** [comment]
绝大部分数据来自中英文的维基百科（[Wikipedia](https://en.wikipedia.org/wiki/Periodic_table)）

**Comment by wersling** [comment]
我并不认为是抄袭，相反作者这个应用功能更多，且中文设计非常好

**Comment by Kyant0** [comment]
Readme 里可说了原创

**Comment by HM-Suiji** [comment]
我也不认为这是抄袭，学习部分ui怎么了？腾讯抄袭的可比这多的多了吧。况且你说的那个软件完全是闭源的，技术栈也大相径庭，这个项目开源让很多人交流学习，就是极好、原创、具有开源精神的项目
